spring.application.name=customer

spring.datasource.url=jdbc:mysql://localhost:3307/ms_customer
spring.datasource.username=seeku
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

life.expectancy.global=71

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html