services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ms_customer'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=seeku'
      - 'MYSQL_PASSWORD=123456'
    ports:
      - '3307:3306'